# Stage 1: build the React frontend
FROM node:22 AS frontend-builder

WORKDIR /build

ARG VITE_STREAM_DELAY=18
ARG VITE_STREAM_PROXY_DELAY=30
ARG VITE_SYNCHRONIZATION_TOLERANCE
ARG VITE_SYNCHRONIZATION_MAX_DEVIATION
ARG VITE_SYNCHRONIZATION_ADJUSTMENT
ARG VITE_SYNCHRONIZATION_MAX_ADJUSTMENT

ENV VITE_STREAM_DELAY=$VITE_STREAM_DELAY
ENV VITE_STREAM_PROXY_DELAY=$VITE_STREAM_PROXY_DELAY
ENV VITE_SYNCHRONIZATION_TOLERANCE=$VITE_SYNCHRONIZATION_TOLERANCE
ENV VITE_SYNCHRONIZATION_MAX_DEVIATION=$VITE_SYNCHRONIZATION_MAX_DEVIATION
ENV VITE_SYNCHRONIZATION_ADJUSTMENT=$VITE_SYNCHRONIZATION_ADJUSTMENT
ENV VITE_SYNCHRONIZATION_MAX_ADJUSTMENT=$VITE_SYNCHRONIZATION_MAX_ADJUSTMENT

COPY frontend/package*.json ./
RUN npm ci

COPY frontend/ ./
RUN npm run build


# Stage 2: backend + bundled frontend
FROM node:22

RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY backend/package*.json ./
RUN npm ci --omit=dev

COPY backend/ ./

# Serve the compiled frontend from /app/public
COPY --from=frontend-builder /build/dist ./public

EXPOSE 5000
CMD ["node", "server.js"]
